### ISSUE TITLE
Running the scanner

### ISSUE THREAD

**Issue by FreshBac0n** [Land3r/Ethersecret-scanner#1]
Hello there!

I'm sorry for asking since programming is a new field of expertise for me, but could you maybe show or explain to me how to get this script to work? I only got so far with Visual Studio Code as to implement the whole master directory/folder into it and start debugging with chrome. After that everything is a mystery for me. Thanks!

**Comment by Land3r** [comment]
Hello,

You will need Visual Studio 2013 or higher and .NET 4.5.2 to compile the solution (or you can upgrade it).
You cannot only use Visual Studio Code for this project.
Additionally, you will need the VC++ 2013 Runtime (https://www.microsoft.com/en-us/download/details.aspx?id=40784) in order to run the underlying cefsharp browser used.

**Comment by ghost** [comment]
Have you tried running this on some AWS or Gcloud? I don’t imagine they would like it that much but might be interesting

**Comment by Land3r** [comment]
I have not tried to run it on some cloud service.
Note that the software is not designed to be run in Azure App services or any other SaaS solution that might be available at AWS or Gcloud.
It requires for the moment a dedicated host to run, so i guess you could still run it under some virtual machines to scale it up.
