### ISSUE TITLE
Json error stops this app from going to the next page

### ISSUE THREAD

**Issue by tazmanny** [Land3r/Ethersecret-scanner#7]
I had added a temporary fix previously to ignore when a page doesnt load completely because it would just hang there and stop working. Now since the website gives a JSON error it will just stop anything from happening unless the pop up is suppressed within the app. A little too advanced for a newbie like me.

**Comment by cryptonoob27** [comment]
So does this fix you posted on my post not actually fix the problem?

`                case 3:
                    if (elm.text() == "") {
                        // At least one element is not loaded.
                        // Wait for elements to load.
                        goToNextPage();
                        return;
                    }
                    else if (elm.text() != '0') {
                        golden = true;
                        foundKey(privateKey, publicKey, elm.text());
                        return;
                    }
                    break;
            }
        });
    });
    if (alreadyRedirected == false) {
        goToNextPage();
    }
}

function goToNextPage() {
    dotnetcallback.callNextPage();
}

function foundKey(privateKey, publicKey, amount) {
    dotnetcallback.foundKey(document.URL, privateKey, publicKey, amount);
}

setTimeout(parseAmmout, 10000);`

**Comment by tazmanny** [comment]
I couldn’t make it suppress that “Json error” pop up. I managed to have the
page refresh if it just hangs due to some balance not loading but if there
is a pop up I couldn’t find a way to bypass or suppress pop ups in that
script.

**Comment by cryptonoob27** [comment]
I think I'm on to something.

In ethers.js I found a part in the code that says "Invalid json response"

It's the only place "Invalid json response" pops up. I searched all the Ether Scanner files and came up empty. I decided to look into ethers.js since Ether Scanner refers to that script many times. In order to change it, it would have to be local correct? Like how Payload.js and StylesInjector.js are in the local "Scripts" folder. 

**So couldn't I save the ethers.js file, make changes to the "invalid json response" portion (maybe delete that portion altogether?), then everywhere in the Ether Scanner code that refers to ethers.js on "http://www.ethersecret.com/dist/ethers.js" change that to the local editted script?**

Excuse my ignorance and lack of understanding, I have pretty much 0 experience in coding. I played with Flash action script, php, and html like 15 years ago lol. I can "edit" pre-made code if it's simple. Most of this is over my head. This error has been driving me crazy so I've been trying to figure it out for a month. I learned a lot as I've been searching through every file and having to look up a majority of terms I run into.

Maybe you can figure it out from here?


```

utils.defineProperty(Provider, 'fetchJSON', function(url, json, processFunc) {

    return new Promise(function(resolve, reject) {
        var request = new XMLHttpRequest();

        if (json) {
            request.open('POST', url, true);
            request.setRequestHeader('Content-Type','application/json');
        } else {
            request.open('GET', url, true);
        }

        request.onreadystatechange = function() {
            if (request.readyState !== 4) { return; }

            try {
                var result = JSON.parse(request.responseText);
            } catch (error) {
                var jsonError = new Error('invalid json response');
                jsonError.orginialError = error;
                jsonError.responseText = request.responseText;
                reject(jsonError);
                return;
            }

            if (processFunc) {
                try {
                    result = processFunc(result);
                } catch (error) {
                    error.url = url;
                    error.body = json;
                    error.responseText = request.responseText;
                    reject(error);
                    return;
                }
            }

            if (request.status != 200) {
                var error = new Error('invalid response - ' + request.status);
                error.statusCode = request.statusCode;
                reject(error);
                return;
            }

            resolve(result);
        };

        request.onerror = function(error) {
            reject(error);
        }

        try {
            if (json) {
                request.send(json);
            } else {
                request.send();
            }

        } catch (error) {
            var connectionError = new Error('connection error');
            connectionError.error = error;
            reject(connectionError);
        }
    });
});


```
![invalid json](https://user-images.githubusercontent.com/37631484/38650332-1a6bdaae-3db0-11e8-8672-67c800b65064.png)

**Comment by tazmanny** [comment]
Brother you have done much more than me. I am

**Comment by tazmanny** [comment]
Brother you have done much more than me. I am a complete newbie here. I
could fix the issue with the scanner hanging on unloaded balances because
it was a simple fix but this Json error is over my head. Hopefully Land3r
can chime in here or someone else and show us the light.

**Comment by foobazz** [comment]
You guys know sites like this are complete bullshit and you could've "generated" those keys with a dedicated local program at MILLIONS OF KEYS per SECOND?

I can't believe this even exists and someone put in the work to create such a program.

Actually this is pretty funny once you're through the rabbit hole. ;)

**Comment by tazmanny** [comment]
YOU mean something like eth vanity ?

**Comment by Land3r** [comment]
@dsqr I agree with you :)
A friend of mine adapted this software to directly ask the balance of account to a Geth node and generate himself the accounts using some nodejs package.

Anyway, this software was a way for me to combine my crypto passion and to POC a website integration into a winform control :)

**Comment by Land3r** [comment]
Regarding this specific issue, a fix was applied by Reanox on his fork of this project : https://github.com/reanox/Ethersecret-scanner

The same solution was applied to this repo.
